spring.application.name=Lesson_Tracker
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
spring.datasource.name=lessonDB
spring.datasource.username=password
spring.datasource.password=myuser
spring.jpa.hibernate.ddl = create
spring.jpa.hibernate.ddl-auto=update

# spring.security.user.name = root
# spring.security.user.password = admin